#!/bin/sh
#; $HOME/.shell/local_aliases
#; Local aliases customized on a "per host" basis.

#echo in ~/.shell/local_maigue/local_aliases
#date

alias j142='export JAVA_HOME=d:/java/j2sdk1.4.2_11'

jeditwin=`cygpath --windows --mixed /d/tools/jEdit_4.3pre2`
jedit ()
{
	# expand the full path of each file
	files=
	for f in $*
	do
		files="$files `cygpath --mixed $f`"
	done
	java -jar $jeditwin/jedit.jar -reuseview -background $files &
}

nppexe=/d/tools/Notepad++/notepad++.exe
npp ()
{
	# expand the full path of each file
	$nppexe `cygpath --mixed --absolute $*`
}

n2exe=/d/tools/notepad2/Notepad2.exe
n2 ()
{
	# expand the full path of each file
	for f in `cygpath --mixed --absolute $*`
	do
		$n2exe $f &
	done
}

editpadliteexe=/d/tools/EditPadLite/EditPadLite.exe
ep ()
{
	# expand the full path of each file
	for f in `cygpath --mixed --absolute $*`
	do
		$editpadliteexe $f &
	done
}

alias vim='VIM=`cygpath -d $VIMRUNTIME` HOME=`cygpath -d $HOME` `cygpath -u $VIMRUNTIME`/gvim.exe' 

##use notepad++ as editor
#export VISUAL=$nppexe
#export EDITOR=$VISUAL
#export SVNEDITOR=$EDITOR

# use vim as editor
export VISUAL=vim
export EDITOR=$VISUAL
export SVNEDITOR=$EDITOR

# generic method to use default editor
ged_old ()
{
	# expand the full path of each file
	files=`cygpath --mixed --absolute $*`
	$EDITOR $files &
}
# VIM version of ged
ged_vim()
{
	# expand the full path of each file
	VIM=`cygpath -d $VIM`
	VIMRUNTIME=`cygpath -d $VIMRUNTIME`
	oldhome=$HOME
	HOME=`cygpath -d $HOME`
	files=`cygpath --mixed --absolute $*`
	`cygpath -u $VIMRUNTIME`/gvim.exe $files &
	HOME=$oldhome
}
# N2 version of ged
ged_n2()
{
	n2 $*
}
# NPP version of ged
ged_npp()
{
	npp $*
}
# EP version of ged
ged_ep()
{
	ep $*
}


#; $Id: local_aliases,v 1.20 2005/02/07 10:53:33 gary Exp $
