#!/bin/bash
#; bashrc
#; Local specific setup

if [ -e ~/shell/.shell/local_lagan/bashrc ]; then
  . ~/shell/.shell/local_lagan/bashrc
fi

#; Gary Added Java
#java=/d/j2sdk1.4.1_01
java=/d/java/jdk1.5.0_01
JAVA_HOME=`cygpath --windows $java`
# put java first to ensure we always pick up the defined one
PATH="$java/bin:$PATH"
export PATH JAVA_HOME

#; Gary Added Maven
if [ ".$MAVEN_HOME" = "." ]; then
	maven=/d/tools/Maven-1.0-rc3
	MAVEN_HOME=`cygpath --windows $maven`
else
	maven=`cygpath --unix "$MAVEN_HOME"`
fi
MAVEN_HOME_LOCAL=`cygpath --windows ~/.maven/plugins`
PATH="$PATH:$maven/bin"
export PATH MAVEN_HOME MAVEN_HOME_LOCAL

#; Gary Added Forrest
if [ ".$FORREST_HOME" = "." ]; then
	forrest=/d/projects/svnroot/forrest
	FORREST_HOME=${forrest}/src/core
else
	forrest=`cygpath --unix "$FORREST_HOME"`
fi
PATH="$PATH:$FORREST_HOME/bin"
export PATH FORREST_HOME

#; Gary Added Groovy
if [ ".$GROOVY_HOME" = "." ]; then
	groovy=/d/tools/groovy-1.0-beta-9
	GROOVY_HOME=`cygpath --windows $groovy`
else
	groovy=`cygpath --unix "$GROOVY_HOME"`
fi
PATH="$PATH:$groovy/bin"
export PATH GROOVY_HOME

#setup Frontline build
#export MY_BUILD_DIR=/d/frontlinebuild
export MY_BUILD_DIR=d:/frontlinebuild
export MY_CD_DIR=/d/frontlinecd
#export MY_EXTRA_LIBS=/d/frontlinebuild/lib
export MY_EXTRA_LIBS=d:/frontlinebuildlib
export MY_JDK_DIR=$java
export MY_ROOT_DIR=/d
export MY_WIN_PATH=`cygpath --unix --sysdir`
#export MY_WIN_PATH=/c/winnt/system32

export MY_BUILD_PREFIX=5-1-1-0


function cmcomplete()
{
    if [ "$PROJECT_BASE" != "" ]
    then
	    cwd=`pwd`;
	    left=`expr "$cwd" : "${PROJECT_BASE}\(.*\)"`
	
	    if [ "$left" != "" ]
	    then

            if [ "$2" != "" ]
            then
                list=`"ls" L:/RCS/$left | grep -e ^$2`
            else
                list=`"ls" L:/RCS/$left`
            fi
            
            COMPREPLY=($list)
	    fi
    fi
}

complete -F cmcomplete cmget
complete -F cmcomplete cmedit
complete -F cmcomplete cminfo

#; $Id: bashrc,v 1.15 2005/02/07 10:53:06 gary Exp $
