#!/bin/sh
#; $HOME/.shell/local_aliases
#; Local aliases customized on a "per host" basis.

alias edit=emacs

EDITOR="edit"
VISUAL="${EDITOR}"
export EDITOR VISUAL
export CVSEDITOR=emacs

#; $Id: local_aliases,v 1.2 2003/06/06 13:36:58 gary Exp $
