#!/bin/bash
#; bashrc
#; Local specific setup

export LOGNAME=gary
export LAGAN_SHELL_TYPE=CYGWIN_BASH
export USERNAME=gary
export USER=gary

#; Gary Added vim
if [ ".$VIM" = "." ]; then
	export VIM=~/shell/vim
fi
if [ ".$VIMRUNTIME" = "." ]; then
	export VIMRUNTIME=/d/tools/Vim/Vim63
fi

#; Setup the default CVS location (buzz).
CVSDEFAULTROOT="/home/cvs/CVSROOT"
export CVSDEFAULTROOT

CVSROOT=":pserver:gary@buzz:${CVSDEFAULTROOT}"
export CVSROOT

#; CVS variables.
CVS_RSH="ssh"
CVSDEFAULTWORKDIR="/e/projects/cvsroot"
CVSWORKDIR="cd ${CVSDEFAULTWORKDIR}"

#; Gary Added Java
JAVAHOME=/d/tools/java/j2sdk1.4.2_04
PATH="$PATH:$JAVAHOME/bin"
JAVA_HOME=`cygpath --windows $JAVAHOME`
export PATH JAVA_HOME

#; Gary Added Maven
if [ ".$MAVEN_HOME" = "." ]; then
	MAVENHOME=/d/tools/maven-1.0-beta-10
	MAVEN_HOME=`cygpath --windows $MAVENHOME`
else
	# convert windows path for cygwin
	MAVENHOME=`cygpath --unix "$MAVEN_HOME"`
fi
PATH="$PATH:$MAVENHOME/bin"
export PATH MAVEN_HOME

PATH="~/tools:$PATH"

#; $Id: bashrc,v 1.5 2004/12/27 20:54:32 gary Exp $
