#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything:
[ -z "$PS1" ] && return

#echo in bashrc
#date

SHELL=bash
export SHELL

cygwin=false
mingw=false
darwin=false
case "`uname`" in
CYGWIN*) cygwin=true;;
MINGW*) mingw=true;;
Darwin*) darwin=true;;
esac

# don't put duplicate lines in the history. See bash(1) for more options
#export HISTCONTROL=ignoredups

# make cygwin case insensitive
#shopt -s nocaseglob

if [ $cygwin == true ]; then
    # convert the initial windows path (replacing space-filled names e.g. Program Files as necessary)
    #export PATHWIN=$PATH
    PATH=`cygpath --mixed --path --short-name "$PATH" | xargs cygpath --unix --path`
    #export PATHORIG=$PATH
    #; Start with a basic PATH - then addon/override in aliases
    PATH="$PATH:/usr/sbin:/bin:/sbin"
	#else just take the path as configured
fi

# unset mail checking
unset MAILCHECK

#; Localised configuration
if [ -f ${HOME}/shell/.shell/local_$NODENAME/bashrc ]; then
#      echo ${HOME}/shell/.shell/local_$NODENAME/bashrc
      . ${HOME}/shell/.shell/local_$NODENAME/bashrc
fi

export PATH

#; Add in local directories, just for fun and convenience
#PATH="/usr/local/bin:/usr/local/sbin:${PATH}"
export PATH

#; Setup a safe $TMP dir
if [ -d "${HOME}/tmp" ]; then
 TMP="${HOME}/tmp"
 TMPDIR="${HOME}/tmp"
 export TMP TMPDIR
else
 mkdir ${HOME}/tmp
 chmod 700 ${HOME}/tmp
 TMP="${HOME}/tmp"
 TMPDIR="${HOME}/tmp"
 export TMP TMPDIR
 echo " ! $TMP was created."
fi

export LOGNAME=gary_mcwilliams

if [ -d ~/shell/tools ]; then
  PATH="~/shell/tools:$PATH"
  if [ -e ~/shell/tools/envmsvc ]; then
      . ~/shell/tools/envmsvc
  fi
fi

if [ -d ~/shell/tools_$NODENAME ]; then
	PATH="~/shell/tools_$NODENAME:$PATH"
fi

# enable color support of ls and also add handy aliases
if [ $mingw == false ] && [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
fi

#echo out bashrc

#; $Id: bashrc,v 1.13 2004/11/30 11:13:34 gary Exp $
