#!/bin/bash
#; bashrc
#; Local specific setup

#echo in ~/shell/.shell/local_bfs-product-55/bashrc
#date

# Delete
#bind '"\e[3~": delete-char'
# Insert
#bind '"\e[2~": paste-from-clipboard' 
# Home
#bind '"\M-[1~": beginning-of-line'
# End
#bind '"\M-[4~": end-of-line'

LOCAL_APPS=/d/Users/gmcwilliams/Applications

#; Gary Added Java
if [ ".$JAVA_HOME" = "." ]; then
	JAVA_HOME=/d/Java/64/jdk1.7.0
fi

#; Gary Added ant
if [ ".$ANT_HOME" = "." ]; then
	ANT_HOME=$LOCAL_APPS/apache-ant-1.8.2
fi

#; Gary Added tomcat
if [ ".$TOMCAT_HOME" = "." ]; then
	TOMCAT_HOME=/d/Tomcat5.5
fi

#; Gary Added Maven2
if [ ".$M2_HOME" = "." ]; then
	MAVEN_HOME=$LOCAL_APPS/apache-maven-2.2.1
	M2_HOME=$MAVEN_HOME
	M2=$M2_HOME/bin
fi
#MAVEN_HOME_LOCAL=/d/home/gary/.maven/plugins
export M2 M2_HOME

#; Gary Added Groovy
if [ ".$GROOVY_HOME" = "." ]; then
	GROOVY_HOME=$LOCAL_APPS/Groovy/Groovy-1.5.7
fi

#; Gary Added vim
if [ ".$VIM" = "." ]; then
	export VIM=$LOCAL_APPS/Vim
fi
if [ ".$VIMRUNTIME" = "." ]; then
	export VIMRUNTIME=$VIM/vim73
	echo $VIMRUNTIME
fi

if [ $cygwin == true ]; then
	JAVA_HOME=`cygpath --windows ${JAVA_HOME}`
	java=`cygpath --unix "$JAVA_HOME"`
	ANT_HOME=`cygpath --windows $ANT_HOME`
	ant=`cygpath --unix "$ANT_HOME"`
	TOMCAT_HOME=`cygpath --windows $TOMCAT_HOME`
	tomcat=`cygpath --unix "$TOMCAT_HOME"`
	MAVEN_HOME=`cygpath --windows $LOCAL_APPS/apache-maven-2.2.1`
	maven=`cygpath --unix "$MAVEN_HOME"`
	GROOVY_HOME=`cygpath --windows $GROOVY_HOME`
	groovy=`cygpath --unix "$GROOVY_HOME"`
	export VIM=`cygpath --mixed $VIM`
	export VIMRUNTIME=`cygpath --mixed $VIMRUNTIME`
fi

# This is a LAGAN box, so add in LAGAN stuff
if [ -e ~/shell/.shell/local_lagan/bashrc ]; then
  . ~/shell/.shell/local_lagan/bashrc
fi

emacs ()
{
#    cd `dirname $1` >/dev/null
#    $emacswin/runemacs.exe `basename $1` >/dev/null &
	# expand the full path of each file
	files=
	for f in $*
	do
	  files="$files `cygpath --windows $f`"
	done
    $emacswin/runemacs.exe $files
}
