#!/bin/bash
#; bashrc
#; Local specific setup

#echo in ~/shell/.shell/local_bfs-product-55/bashrc
#date

LOCAL_APPS=/d/Users/gmcwilliams/Applications

#; Gary Added Java
if [ ".$JAVA_HOME" = "." ]; then
	JAVA_HOME=`cygpath --windows /d/java/64/jdk1.6.0_24`
fi
if [ -d $JAVA_HOME ]; then
	java=`cygpath --unix "$JAVA_HOME"`
fi

#; Gary Added ant
if [ ".$ANT_HOME" = "." ]; then
	ANT_HOME=`cygpath --windows $LOCAL_APPS/apache-ant-1.8.1`
fi
if [ -d $ANT_HOME ]; then
	ant=`cygpath --unix "$ANT_HOME"`
fi

#; Gary Added tomcat
if [ ".$TOMCAT_HOME" = "." ]; then
	TOMCAT_HOME=`cygpath --windows /d/Tomcat5.5`
fi
if [ -d $TOMCAT_HOME ]; then
	tomcat=`cygpath --unix "$TOMCAT_HOME"`
fi

#; Gary Added Maven2
if [ ".$M2_HOME" = "." ]; then
	MAVEN_HOME=`cygpath --windows $LOCAL_APPS/apache-maven-2.2.1`
	M2_HOME=$MAVEN_HOME
	M2=$M2_HOME/bin
fi
maven=`cygpath --unix "$MAVEN_HOME"`
#MAVEN_HOME_LOCAL=/d/home/gary/.maven/plugins
export M2 M2_HOME

#; Gary Added Groovy
# let lagan bashrc configure it
if [ ".$GROOVY_HOME" = "." ]; then
	groovy=/d/tools/Groovy/Groovy-1.5.7
else
	groovy=`cygpath --unix "$GROOVY_HOME"`
fi

#; Gary Added vim
if [ ".$VIM" = "." ]; then
	export VIM=`cygpath --mixed $LOCAL_APPS/Vim`
fi
if [ ".$VIMRUNTIME" = "." ]; then
	export VIMRUNTIME=`cygpath --mixed $VIM/vim73`
	echo $VIMRUNTIME
fi

# This is a LAGAN box, so add in LAGAN stuff
if [ -e ~/shell/.shell/local_lagan/bashrc ]; then
  . ~/shell/.shell/local_lagan/bashrc
fi
