#!/bin/bash
#; bashrc
#; Local specific setup

#echo in ~/shell/.shell/local_lagan/bashrc
#date

#; configure generic tools
if [ -d ~/shell/tools_lagan ]; then
  PATH=~/shell/tools_lagan:$PATH
fi

#; configure local tools
if [ -d ~/shell/tools_$NODENAME ]; then
  PATH=~/shell/tools_$NODENAME:$PATH
fi

# The local tools may just configure path settings. If so, we should setup here
if [ ".$java" != "." ]; then
	JAVA_HOME=`cygpath --mixed $java`
	#echo java $JAVA_HOME
	# put java first to ensure we always pick up the defined one
	PATH="$java/bin:$PATH"
	export PATH JAVA_HOME
fi

if [ ".$ant" != "." ]; then
	PATH="$PATH:$ant/bin"
	export PATH ANT_HOME
fi

if [ ".$maven" != "." ]; then
	PATH="$PATH:$maven/bin"
	export PATH MAVEN_HOME MAVEN_HOME_LOCAL
fi

if [ ".$groovy" != "." ]; then
	PATH="$PATH:$groovy/bin"
	MY_GROOVY_DIR=$groovy/bin
	export PATH GROOVY_HOME MY_GROOVY_DIR
fi


#; configure generic aliases
if [ -f ~/shell/.shell/local_lagan/local_aliases ]; then
  . ~/shell/.shell/local_lagan/local_aliases
fi

#; SVN variables
SVN_SSH='ssh -l gary'
export SVN_SSH

set -o vi
