#!/bin/sh
#; $HOME/.shell/local_aliases
#; Local aliases customized on a "per host" basis.

#echo in ~/shell/.shell/local_lagan/local_aliases
#date

#; override default for local machine setup

#; $Id: local_aliases,v 1.4 2004/12/17 14:03:12 gary Exp $
