#! /bin/bash
#
# script to remove readonly files from current dir
#

find . -not -perm -ugo=w -print | xargs rm -f

# following is 'correct' version, but it's suddenly stopped working!!!
#  find . -name "*.$codetype" -perm +u=w | xargs ls -l

# $Id: removereadonly,v 1.1 2004/07/27 11:55:21 gary Exp $
