#!/bin/bash
#
# script to clean out 'old' build remnant before a new build occurs.
#

outputusage()
{
	echo "Usage: setupbuild [-c] [-l] [-o] [-n] [-p \"ARGS\"]"
	echo "   setupbuild will build the version of frontline"
	echo "   -c : clean the build destination before building"
	echo "   -l : do *not* log the output"
	echo "   -o : do *not* obfuscate"
	echo "   -n : do *not* sign"
	echo "   -e : Build into the eclipse environment"
	echo "   -p : pass on elements contained within \"ARGS\" to the setupbuild process"
	exit 2
}


usev=${FLVER:-"none"}
if [ $usev = "none" ]
then
	echo no FLVER set
	outputusage
	exit
fi


vermajor=`echo $usev | cut -d- -f1`
verrelse=`echo $usev | cut -d- -f2`
verminor=`echo $usev | cut -d- -f3`
verbuild=`echo $usev | cut -d- -f4`

clean=n
log=y
eclipse=n
valid=1
passthrough=
obfuscate=
sign=

OPTIND=1
while getopts "celonp:" Option
do
  case $Option in
    c     ) clean=y;;
    l     ) log=n;;
    e     ) eclipse=y;;
    o     ) obfuscate=-o;;
    n     ) sign=-n;;
    p     ) passthrough=$OPTARG;;
    *     ) valid=0;;   # DEFAULT, any other options are invalid
  esac
done

shift $(($OPTIND - 1))

if [ $valid = 0 ]
then
	outputusage
fi

echo "using Version $usev environment"
if [ $eclipse = "y" ]
then
	. envbuild -e
else
	. envbuild
fi

# only clean up the standard build environment
if [ $clean = "y" -a $eclipse = "n" ];
then
	cleanbuild
fi

cd $MY_ROOT_DIR/projects/lagancentre/build/frontline/buildscripts

if [ ! -f ./setupbuild.ksh ];
then
  echo "could not find ./setupbuild.ksh, you are not in correct directory"
  echo "you are in `pwd`"
  exit
fi


echo "build dir: $MY_BUILD_DIR"

export BASH_ENV=/h/shell/tools_lagan/buildshell
. /h/shell/tools_lagan/buildshell

mycommand="./setupbuild.ksh $obfuscate $sign $passthrough"
echo $mycommand

if [ $log = "y" ];
then
	logfile=$MY_ROOT_DIR/setupbuild.log
	echo logging to $logfile
	bash $mycommand > $logfile 2>&1
	grep -A 2 -i "\^" $logfile 2>&1 >/dev/null
	ok=$?
	if [ "$ok" = "0" ]; then
		echo "compilation errors found"
		grep -B 4 -i "\^" $logfile
	fi
else
	bash $mycommand
fi

# $Id: setupbuild,v 1.2 2004/12/15 17:47:15 gary Exp $
