#!/bin/bash
#
# script to work on set of files specified so that they can be
# smcreate'd within RCS
#

outputusage()
{
	echo "Usage: `basename $0` -p PCC_number -v frontlineversion [-g]"
	echo "   You need to run checkdiffs first to create the input file 'smcreate'"
	echo "   `basename $0` will smcreate files with the defined PCC number"
	echo "   -v allows the specification of the version string to be used"
	echo "      if no -v is given then the version defined in the PCCVER env var is used"
	echo "   -g will perform a cmget on the file after the smcreate"
	exit 2
}

pcc=${PCC:-""}
get=0
valid=1
ver=${PCCVER:-""}

while getopts ":p:v:g" Option
do
  case $Option in
    p     ) case $OPTARG in
		      0)                                pcc=$OPTARG;;
		      PCC_[0-9][0-9][0-9][0-9][0-9])	pcc=$OPTARG;;
		      PDF_[0-9][0-9][0-9][0-9][0-9])	pcc=$OPTARG;;
     	      *)	                            valid=0;;
          esac;;
    v     ) case $OPTARG in
		      [0-9]\.[0-9]\.[0-9])	ver=$OPTARG;;
     	      *)	                valid=0;;
          esac;;
    g     ) get=1;;
    *     ) valid=0;;   # DEFAULT
  esac
done

#echo msg=$msg
echo pcc=$pcc
echo ver=$ver
#echo valid=$valid
#exit

if [ "x$pcc" = "x" ]; then
	valid=0
fi

if [ "x$ver" = "x" ]; then
	echo "you must specify a valid frontline version"
	valid=0
fi

if [ $valid = 0 ]; then
	echo "invalid option specified, please check"
	outputusage
fi

shift $(($OPTIND - 1))

#checkdiffs

for f in `cat smcreate`
do
	echo $f
	chmod +w $f
	smcreate $f <<EOF
$pcc
$ver
$f
EOF
#	cmedit $f
	if [ $get = 1 ]; then
		cmget $f
	fi
done

rm -f smcreate
rm -f *.diff

# $Id: smcreate_latest,v 1.4 2004/04/27 10:50:40 gary Exp $
